
import type { Equipment } from './types';

export const equipmentData: Equipment[] = [
  {
    id: '1',
    name: 'Industrial 3D Printer',
    model: 'Stratasys F900',
    serialNumber: 'SN-F900-1001',
    purchaseDate: '2022-01-15',
    warrantyEndDate: '2024-01-15',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [
      { 
        id: 'c1', 
        provider: 'Stratasys Support', 
        startDate: '2024-01-15', 
        endDate: '2025-01-14', 
        renewalDate: '2024-12-15', 
        terms: 'Full coverage for parts and labor.',
        numberOfPreventativeMaintenance: 2,
        preventativeMaintenanceDueDate: '2024-09-01',
        poStartDate: '2024-01-10',
        poEndDate: '2025-01-10',
        poNumber: 'PO-SC-123',
        poLineNumber: '1',
        annualCost: 5000,
        creditUnusedCoverage: false,
        vendorPoc: 'Alice Williams',
      },
      { 
        id: 'c1-old', 
        provider: 'Stratasys Support', 
        startDate: '2022-01-15', 
        endDate: '2024-01-14', 
        renewalDate: '2023-12-15', 
        terms: 'Initial 2-year warranty support.',
        annualCost: 4500,
      },
    ],
    documents: [
      { id: 'd1', name: 'F900 User Manual.pdf', type: 'Manual', uploadDate: '2022-01-15', url: '#' },
      { id: 'd2', name: 'Warranty Certificate.pdf', type: 'Warranty', uploadDate: '2022-01-15', url: '#' },
    ],
    software: [
      { id: 's1', name: 'GrabCAD Print', version: '1.57', licenseKey: 'LICENSE-GC-XYZ', installDate: '2022-01-15' },
    ],
    serviceLogs: [
      { id: 'sl1', date: '2023-07-20', type: 'Preventative', technician: 'John Doe', notes: 'Completed annual preventative maintenance. Replaced print head and calibrated axes.' },
      { id: 'sl2', date: '2024-02-10', type: 'Repair', technician: 'Jane Smith', notes: 'Replaced faulty heating element. System is back online.' },
    ],
    room: 'B-101',
    department: 'R&D',
    manufacturer: 'Stratasys',
    nciNumber: 'NCI-00123',
    nihNumber: 'NIH-98765',
    transferred: false,
    poc: 'Dr. Evelyn Reed',
    notes: 'Primary printer for advanced polymer prototypes.',
    purchasingAmbisPoNumber: 'PO-2022-001',
    installedDate: '2022-01-20',
    node: 'N-123',
    probe: 'P-456',
    onNetwork: true,
    computerAssociated: '192.168.1.101',
  },
  {
    id: '2',
    name: 'CNC Milling Machine',
    model: 'Haas VF-2',
    serialNumber: 'SN-HAAS-2002',
    purchaseDate: '2021-03-20',
    warrantyEndDate: '2023-03-20',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [
      { id: 'd3', name: 'Haas VF-2 Manual.pdf', type: 'Manual', uploadDate: '2021-03-20', url: '#' },
    ],
    software: [
      { id: 's2', name: 'Haas Control Software', version: '11.82', licenseKey: 'N/A', installDate: '2021-03-20' },
    ],
    serviceLogs: [
      { id: 'sl3', date: '2023-09-01', type: 'Preventative', technician: 'Mike Rivera', notes: 'Quarterly maintenance check. Lubricated all moving parts and checked fluid levels.' },
    ],
    room: 'C-205',
    department: 'Manufacturing',
    manufacturer: 'Haas Automation',
    nciNumber: 'NCI-00124',
    nihNumber: 'NIH-98766',
    transferred: false,
    poc: 'John Miller',
    notes: 'Used for high-precision metal parts.',
    purchasingAmbisPoNumber: 'PO-2021-002',
    installedDate: '2021-03-25',
    onNetwork: false,
  },
  {
    id: '3',
    name: 'Lab Spectrometer',
    model: 'Thermo Scientific Nicolet iS50',
    serialNumber: 'SN-TS-3003',
    purchaseDate: '2023-06-01',
    warrantyEndDate: '2025-06-01',
    status: 'In-Repair',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [
      { 
        id: 'c2', 
        provider: 'Thermo Fisher Scientific', 
        startDate: '2023-06-01', 
        endDate: '2026-05-31', 
        renewalDate: '2026-05-01', 
        terms: 'Gold Support Plan with on-site service.',
        annualCost: 7500,
        vendorPoc: 'Support Team',
      },
    ],
    documents: [
        { id: 'd4', name: 'Nicolet iS50 Manual.pdf', type: 'Manual', uploadDate: '2023-06-01', url: '#' },
        { id: 'd5', name: 'Purchase Invoice.pdf', type: 'Invoice', uploadDate: '2023-06-01', url: '#' },
    ],
    software: [
      { id: 's3', name: 'OMNIC Software', version: '9.12', licenseKey: 'LICENSE-OMNIC-ABC', installDate: '2023-06-01' },
    ],
    serviceLogs: [
        { id: 'sl4', date: '2024-05-15', type: 'Repair', technician: 'Support Team', notes: 'Laser assembly malfunction. Awaiting replacement part.' },
    ],
    room: 'A-310',
    department: 'Quality Assurance',
    manufacturer: 'Thermo Fisher Scientific',
    nciNumber: 'NCI-00125',
    nihNumber: 'NIH-98767',
    transferred: true,
    poc: 'Dr. Sarah Chen',
    notes: 'Critical for material analysis.',
    purchasingAmbisPoNumber: 'PO-2023-003',
    installedDate: '2023-06-05',
    onNetwork: true,
    computerAssociated: '00:1B:44:11:3A:B7',
  },
  {
    id: '4',
    name: 'High-Speed Centrifuge',
    model: 'Beckman Coulter Avanti JXN-30',
    serialNumber: 'SN-BC-4004',
    purchaseDate: '2020-11-01',
    warrantyEndDate: '2022-11-01',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [{
        id: 'c3',
        provider: 'Beckman Coulter Service',
        startDate: '2022-11-01',
        endDate: '2024-10-31',
        renewalDate: '2024-10-01',
        terms: 'Basic preventative maintenance plan.',
        numberOfPreventativeMaintenance: 1,
        preventativeMaintenanceDoneDate: '2024-04-10',
        preventativeMaintenanceDueDate: '2024-10-10',
        annualCost: 2500,
    }],
    documents: [],
    software: [],
    serviceLogs: [
        { id: 'sl5', date: '2024-04-10', type: 'Preventative', technician: 'BC Service', notes: 'Annual PM completed.'}
    ],
    room: 'D-102',
    department: 'Biochemistry',
    manufacturer: 'Beckman Coulter',
    nciNumber: 'NCI-00201',
    nihNumber: 'NIH-98801',
    transferred: false,
    poc: 'Dr. Ben Carter',
    notes: 'Rotor must be balanced carefully.',
    purchasingAmbisPoNumber: 'PO-2020-115',
    installedDate: '2020-11-05',
    onNetwork: false,
  },
  {
    id: '5',
    name: 'Confocal Microscope',
    model: 'Leica TCS SP8',
    serialNumber: 'SN-LE-5005',
    purchaseDate: '2022-08-19',
    warrantyEndDate: '2024-08-19',
    status: 'Decommissioned',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [
      { id: 'd6', name: 'Leica SP8 Manual.pdf', type: 'Manual', uploadDate: '2022-08-19', url: '#' },
      { id: 'd7', name: 'Decommissioning Report.pdf', type: 'Other', uploadDate: '2024-06-01', url: '#' },
    ],
    software: [
      { id: 's4', name: 'LAS X', version: '3.7', licenseKey: 'LICENSE-LASX-DEF', installDate: '2022-08-20' },
    ],
    serviceLogs: [
        { id: 'sl6', date: '2024-05-20', type: 'Repair', technician: 'Self', notes: 'Power supply failed. Unit is beyond economical repair.'},
        { id: 'sl7', date: '2024-06-01', type: 'Inspection', technician: 'Admin', notes: 'Unit decommissioned and scheduled for surplus.'}
    ],
    room: 'E-401',
    department: 'Cell Biology',
    manufacturer: 'Leica Microsystems',
    nciNumber: 'NCI-00220',
    nihNumber: 'NIH-98820',
    transferred: false,
    poc: 'Dr. Chloe Davis',
    notes: 'Decommissioned due to irreparable power supply failure.',
    purchasingAmbisPoNumber: 'PO-2022-050',
    installedDate: '2022-08-20',
    onNetwork: true,
    computerAssociated: '192.168.1.105',
  },
  {
    id: '6',
    name: 'PCR Machine',
    model: 'Bio-Rad CFX96',
    serialNumber: 'SN-BR-6006',
    purchaseDate: '2023-01-30',
    warrantyEndDate: '2025-01-30',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'B-105',
    department: 'Genetics',
    manufacturer: 'Bio-Rad',
    nciNumber: 'NCI-00301',
    nihNumber: 'NIH-98901',
    transferred: false,
    poc: 'Dr. Frank White',
    notes: '',
    purchasingAmbisPoNumber: 'PO-2023-011',
    installedDate: '2023-02-05',
    onNetwork: true,
    computerAssociated: '192.168.1.106'
  },
  {
    id: '7',
    name: 'Flow Cytometer',
    model: 'BD FACSAria III',
    serialNumber: 'SN-BD-7007',
    purchaseDate: '2019-07-14',
    warrantyEndDate: '2021-07-14',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [{
        id: 'c4',
        provider: 'BD Biosciences Service',
        startDate: '2021-07-14',
        endDate: '2024-07-13',
        renewalDate: '2024-06-14'
    }],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'D-210',
    department: 'Immunology',
    manufacturer: 'BD Biosciences',
    nciNumber: 'NCI-00180',
    nihNumber: 'NIH-98780',
    transferred: false,
    poc: 'Dr. Grace Lee',
    notes: 'Requires daily calibration.',
    purchasingAmbisPoNumber: 'PO-2019-088',
    installedDate: '2019-07-20',
    onNetwork: true,
    computerAssociated: '192.168.1.107'
  },
  {
    id: '8',
    name: 'Autoclave',
    model: 'Steris Amsco Evolution',
    serialNumber: 'SN-ST-8008',
    purchaseDate: '2022-05-22',
    warrantyEndDate: '2024-05-22',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'C-101',
    department: 'Lab Support',
    manufacturer: 'Steris',
    nciNumber: 'NCI-00250',
    nihNumber: 'NIH-98850',
    transferred: false,
    poc: 'Lab Manager',
    notes: 'Weekly spore testing required.',
    purchasingAmbisPoNumber: 'PO-2022-023',
    installedDate: '2022-05-30',
    onNetwork: false
  },
  {
    id: '9',
    name: 'Liquid Handler',
    model: 'Hamilton STAR',
    serialNumber: 'SN-HM-9009',
    purchaseDate: '2023-10-01',
    warrantyEndDate: '2025-10-01',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'A-401',
    department: 'High-Throughput Screening',
    manufacturer: 'Hamilton',
    nciNumber: 'NCI-00400',
    nihNumber: 'NIH-99000',
    transferred: false,
    poc: 'Dr. Heidi Chen',
    notes: '',
    purchasingAmbisPoNumber: 'PO-2023-090',
    installedDate: '2023-10-10',
    onNetwork: true,
    computerAssociated: '192.168.1.109'
  },
  {
    id: '10',
    name: 'Freeze Dryer',
    model: 'Labconco FreeZone',
    serialNumber: 'SN-LC-1010',
    purchaseDate: '2021-08-15',
    warrantyEndDate: '2023-08-15',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'E-110',
    department: 'Sample Prep',
    manufacturer: 'Labconco',
    nciNumber: 'NCI-00211',
    nihNumber: 'NIH-98811',
    transferred: false,
    poc: 'Ivan Petrov',
    notes: 'Check vacuum pump oil monthly.',
    purchasingAmbisPoNumber: 'PO-2021-077',
    installedDate: '2021-08-20',
    onNetwork: false
  },
  {
    id: '11',
    name: 'Gel Imager',
    model: 'Azure Biosystems c600',
    serialNumber: 'SN-AZ-1111',
    purchaseDate: '2024-01-10',
    warrantyEndDate: '2026-01-10',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'B-107',
    department: 'Molecular Biology',
    manufacturer: 'Azure Biosystems',
    nciNumber: 'NCI-00501',
    nihNumber: 'NIH-99101',
    transferred: false,
    poc: 'Dr. Judy King',
    notes: 'For chemiluminescence and fluorescence imaging.',
    purchasingAmbisPoNumber: 'PO-2024-001',
    installedDate: '2024-01-15',
    onNetwork: true,
    computerAssociated: '192.168.1.111'
  },
  {
    id: '12',
    name: 'Water Purification System',
    model: 'Millipore Milli-Q IQ 7000',
    serialNumber: 'SN-MP-1212',
    purchaseDate: '2022-09-01',
    warrantyEndDate: '2023-09-01',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [{
        id: 'c5',
        provider: 'Millipore Sigma Service',
        startDate: '2023-09-01',
        endDate: '2025-08-31',
        renewalDate: '2025-08-01',
        terms: 'Annual filter replacement and system check.',
    }],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'C-101',
    department: 'Lab Support',
    manufacturer: 'Millipore Sigma',
    nciNumber: 'NCI-00255',
    nihNumber: 'NIH-98855',
    transferred: false,
    poc: 'Lab Manager',
    notes: 'Change cartridges as prompted.',
    purchasingAmbisPoNumber: 'PO-2022-075',
    installedDate: '2022-09-05',
    onNetwork: false
  },
  {
    id: '13',
    name: 'Plate Reader',
    model: 'Molecular Devices SpectraMax i3x',
    serialNumber: 'SN-MD-1313',
    purchaseDate: '2020-02-20',
    warrantyEndDate: '2022-02-20',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'A-402',
    department: 'High-Throughput Screening',
    manufacturer: 'Molecular Devices',
    nciNumber: 'NCI-00405',
    nihNumber: 'NIH-99005',
    transferred: false,
    poc: 'Dr. Ken Long',
    notes: '',
    purchasingAmbisPoNumber: 'PO-2020-015',
    installedDate: '2020-02-25',
    onNetwork: true,
    computerAssociated: '192.168.1.113'
  },
  {
    id: '14',
    name: 'Fume Hood',
    model: 'Labconco Protector Premier',
    serialNumber: 'SN-LC-1414',
    purchaseDate: '2019-01-15',
    warrantyEndDate: '2020-01-15',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [{ id: 'sl8', date: '2024-01-10', type: 'Inspection', technician: 'EHS', notes: 'Annual certification passed.'}],
    room: 'D-105',
    department: 'Chemistry',
    manufacturer: 'Labconco',
    nciNumber: 'NCI-00190',
    nihNumber: 'NIH-98790',
    transferred: false,
    poc: 'Lab Manager',
    notes: 'Annual EHS certification required.',
    purchasingAmbisPoNumber: 'PO-2019-005',
    installedDate: '2019-01-20',
    onNetwork: false
  },
  {
    id: '15',
    name: 'DNA Sequencer',
    model: 'Illumina NovaSeq 6000',
    serialNumber: 'SN-IL-1515',
    purchaseDate: '2022-12-01',
    warrantyEndDate: '2024-12-01',
    status: 'In-Repair',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [{ id: 'sl9', date: '2024-06-15', type: 'Repair', technician: 'Illumina FSE', notes: 'Fluidics system error. Field service engineer dispatched.'}],
    room: 'B-210',
    department: 'Genomics Core',
    manufacturer: 'Illumina',
    nciNumber: 'NCI-00310',
    nihNumber: 'NIH-98910',
    transferred: false,
    poc: 'Dr. Laura Martinez',
    notes: 'High-throughput sequencing.',
    purchasingAmbisPoNumber: 'PO-2022-100',
    installedDate: '2022-12-10',
    onNetwork: true,
    computerAssociated: '192.168.1.115'
  },
  {
    id: '16',
    name: 'Microtome',
    model: 'Leica RM2255',
    serialNumber: 'SN-LE-1616',
    purchaseDate: '2023-04-10',
    warrantyEndDate: '2025-04-10',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'E-301',
    department: 'Pathology',
    manufacturer: 'Leica Biosystems',
    nciNumber: 'NCI-00230',
    nihNumber: 'NIH-98830',
    transferred: false,
    poc: 'Dr. Michael Brown',
    notes: 'Change blade daily.',
    purchasingAmbisPoNumber: 'PO-2023-018',
    installedDate: '2023-04-15',
    onNetwork: false
  },
  {
    id: '17',
    name: ' Incubator',
    model: 'Thermo Fisher Heracell VIOS 160i',
    serialNumber: 'SN-TS-1717',
    purchaseDate: '2021-05-25',
    warrantyEndDate: '2023-05-25',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'B-102',
    department: 'Cell Culture',
    manufacturer: 'Thermo Fisher Scientific',
    nciNumber: 'NCI-00280',
    nihNumber: 'NIH-98880',
    transferred: false,
    poc: 'Nancy Green',
    notes: 'CO2 tank replaced weekly.',
    purchasingAmbisPoNumber: 'PO-2021-030',
    installedDate: '2021-06-01',
    onNetwork: false
  },
  {
    id: '18',
    name: 'Mass Spectrometer',
    model: 'Agilent 6546 Q-TOF',
    serialNumber: 'SN-AG-1818',
    purchaseDate: '2023-08-01',
    warrantyEndDate: '2025-08-01',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'D-330',
    department: 'Proteomics',
    manufacturer: 'Agilent',
    nciNumber: 'NCI-00350',
    nihNumber: 'NIH-98950',
    transferred: false,
    poc: 'Dr. Oscar Perez',
    notes: 'Requires stable temperature and humidity.',
    purchasingAmbisPoNumber: 'PO-2023-065',
    installedDate: '2023-08-10',
    onNetwork: true,
    computerAssociated: '192.168.1.118'
  },
  {
    id: '19',
    name: 'Digital Droplet PCR System',
    model: 'Bio-Rad QX200',
    serialNumber: 'SN-BR-1919',
    purchaseDate: '2022-10-10',
    warrantyEndDate: '2024-10-10',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'B-106',
    department: 'Genetics',
    manufacturer: 'Bio-Rad',
    nciNumber: 'NCI-00305',
    nihNumber: 'NIH-98905',
    transferred: false,
    poc: 'Dr. Patricia Hall',
    notes: 'Absolute quantification of nucleic acids.',
    purchasingAmbisPoNumber: 'PO-2022-085',
    installedDate: '2022-10-15',
    onNetwork: true,
    computerAssociated: '192.168.1.119'
  },
  {
    id: '20',
    name: 'X-Ray Diffractometer',
    model: 'Bruker D8 ADVANCE',
    serialNumber: 'SN-BK-2020',
    purchaseDate: '2018-06-01',
    warrantyEndDate: '2020-06-01',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [{
        id: 'c6',
        provider: 'Bruker Service',
        startDate: '2020-06-01',
        endDate: '2025-05-31',
        renewalDate: '2025-05-01'
    }],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'G-101',
    department: 'Material Science',
    manufacturer: 'Bruker',
    nciNumber: 'NCI-00150',
    nihNumber: 'NIH-98750',
    transferred: false,
    poc: 'Dr. Quinn Taylor',
    notes: 'Safety checks must be performed before each use.',
    purchasingAmbisPoNumber: 'PO-2018-040',
    installedDate: '2018-06-10',
    onNetwork: true,
    computerAssociated: '192.168.1.120'
  },
  {
    id: '21',
    name: 'Homogenizer',
    model: 'Omni TH-01',
    serialNumber: 'SN-OM-2121',
    purchaseDate: '2023-03-03',
    warrantyEndDate: '2025-03-03',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'E-111',
    department: 'Sample Prep',
    manufacturer: 'Omni International',
    nciNumber: 'NCI-00215',
    nihNumber: 'NIH-98815',
    transferred: false,
    poc: 'Rachel Adams',
    notes: 'Clean probes thoroughly after each use.',
    purchasingAmbisPoNumber: 'PO-2023-013',
    installedDate: '2023-03-05',
    onNetwork: false
  },
  {
    id: '22',
    name: 'Slide Scanner',
    model: 'Hamamatsu NanoZoomer S360',
    serialNumber: 'SN-HM-2222',
    purchaseDate: '2022-11-20',
    warrantyEndDate: '2024-11-20',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'E-305',
    department: 'Digital Pathology',
    manufacturer: 'Hamamatsu',
    nciNumber: 'NCI-00235',
    nihNumber: 'NIH-98835',
    transferred: false,
    poc: 'Dr. Samuel Roberts',
    notes: 'High-throughput whole slide imaging.',
    purchasingAmbisPoNumber: 'PO-2022-095',
    installedDate: '2022-11-28',
    onNetwork: true,
    computerAssociated: '192.168.1.122'
  },
  {
    id: '23',
    name: 'Vacuum Oven',
    model: 'Across International VO-16050',
    serialNumber: 'SN-AI-2323',
    purchaseDate: '2023-07-07',
    warrantyEndDate: '2025-07-07',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'D-108',
    department: 'Chemistry',
    manufacturer: 'Across International',
    nciNumber: 'NCI-00195',
    nihNumber: 'NIH-98795',
    transferred: false,
    poc: 'Dr. Tina Diaz',
    notes: '',
    purchasingAmbisPoNumber: 'PO-2023-055',
    installedDate: '2023-07-10',
    onNetwork: false
  },
  {
    id: '24',
    name: 'Real-Time PCR System',
    model: 'Applied Biosystems QuantStudio 7 Flex',
    serialNumber: 'SN-AB-2424',
    purchaseDate: '2021-09-10',
    warrantyEndDate: '2023-09-10',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: true,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'B-108',
    department: 'Genetics',
    manufacturer: 'Applied Biosystems',
    nciNumber: 'NCI-00308',
    nihNumber: 'NIH-98908',
    transferred: false,
    poc: 'Dr. Uma Vance',
    notes: 'Used for gene expression analysis.',
    purchasingAmbisPoNumber: 'PO-2021-081',
    installedDate: '2021-09-15',
    onNetwork: true,
    computerAssociated: '192.168.1.124'
  },
  {
    id: '25',
    name: 'Electrophoresis System',
    model: 'Bio-Rad ChemiDoc MP',
    serialNumber: 'SN-BR-2525',
    purchaseDate: '2024-02-20',
    warrantyEndDate: '2026-02-20',
    status: 'Active',
    imageUrl: 'https://placehold.co/100x100.png',
    hasServiceContract: false,
    contracts: [],
    documents: [],
    software: [],
    serviceLogs: [],
    room: 'B-109',
    department: 'Molecular Biology',
    manufacturer: 'Bio-Rad',
    nciNumber: 'NCI-00510',
    nihNumber: 'NIH-99110',
    transferred: false,
    poc: 'Victor Wu',
    notes: 'Gel and blot imaging.',
    purchasingAmbisPoNumber: 'PO-2024-008',
    installedDate: '2024-02-25',
    onNetwork: true,
    computerAssociated: '192.168.1.125'
  },
  ...Array.from({ length: 75 }, (_, i) => {
    const id = 26 + i;
    const purchaseYear = 2020 + (i % 5);
    const hasContract = Math.random() > 0.4;
    const onNetwork = Math.random() > 0.5;
    const statusOptions: ('Active' | 'In-Repair' | 'Decommissioned')[] = ['Active', 'Active', 'Active', 'In-Repair', 'Decommissioned'];
    return {
      id: `${id}`,
      name: `Equipment ${id}`,
      model: `Model-X${id}`,
      serialNumber: `SN-EQ-${1000 + id}`,
      purchaseDate: `${purchaseYear}-01-15`,
      warrantyEndDate: `${purchaseYear + 2}-01-15`,
      status: statusOptions[i % 5],
      imageUrl: 'https://placehold.co/100x100.png',
      hasServiceContract: hasContract,
      contracts: hasContract ? [
        {
          id: `c-${id}`,
          provider: `Vendor ${id}`,
          startDate: `${purchaseYear + 2}-01-15`,
          endDate: `${purchaseYear + 3}-01-14`,
          renewalDate: `${purchaseYear + 2}-12-15`,
          terms: 'Standard coverage.',
          annualCost: 1000 + (i * 50),
          vendorPoc: `Vendor POC ${id}`
        }
      ] : [],
      documents: [
        { id: `d-${id}`, name: `Manual_${id}.pdf`, type: 'Manual' as const, uploadDate: `${purchaseYear}-01-15`, url: '#' },
      ],
      software: onNetwork ? [
        { id: `s-${id}`, name: `Control Software ${id}`, version: `${i % 3 + 1}.0`, licenseKey: `LICENSE-${id}`, installDate: `${purchaseYear}-01-20` },
      ] : [],
      serviceLogs: [
        { id: `sl-${id}-1`, date: `${purchaseYear + 1}-06-10`, type: 'Preventative' as const, technician: 'Tech A', notes: 'Routine check-up.' },
        ... (i % 4 === 0 ? [{ id: `sl-${id}-2`, date: `${purchaseYear + 2}-03-05`, type: 'Repair' as const, technician: 'Tech B', notes: 'Component replaced.' }] : [])
      ],
      room: `R-${100 + (i % 20)}`,
      department: `Dept-${String.fromCharCode(65 + (i % 10))}`,
      manufacturer: `Manufacturer ${String.fromCharCode(65 + (i % 15))}`,
      nciNumber: `NCI-00${300 + id}`,
      nihNumber: `NIH-98${900 + id}`,
      transferred: i % 10 === 0,
      poc: `User ${id}`,
      notes: `Note for equipment ${id}.`,
      purchasingAmbisPoNumber: `PO-${purchaseYear}-${id}`,
      installedDate: `${purchaseYear}-01-20`,
      node: onNetwork && i % 3 === 0 ? `N-${150+i}` : undefined,
      probe: onNetwork && i % 3 === 0 ? `P-${500+i}`: undefined,
      onNetwork: onNetwork,
      computerAssociated: onNetwork ? `192.168.1.${126 + i}` : undefined
    }
  })
];

    